### ISSUE TITLE
Binary is incompatible with Swift 3.2

### ISSUE THREAD

**Issue by aapierce0** [LivePersonInc/iOSFrameworks#1]
Version 2.7.0.20.1078 appears to be compiled with Swift 3.1 which means the framework is not compatible with Swift 3.2 (for Xcode 9 and iOS 11)

**Comment by nirlachman-liveperson** [comment]
Please check 'Swift 4.0' branch.
Thanks

**Comment by aapierce0** [comment]
I don't see the Swift 4.0 branch. All I see is the master branch.

Can you point me in the right direction?

**Comment by nirlachman-liveperson** [comment]
@aapierce0  i'm really sorry but this repository is incorrect.
Please use ONLY this one:
https://github.com/LP-Messaging/iOS-Messaging-SDK

It has the latest version and also 'Swift_4.0' branch.

Thanks!

**Comment by aapierce0** [comment]
Okay, thank you.

FYI: The latest version in the podspec at [LivePersonInc/iOSPodSpecs](https://github.com/LivePersonInc/iOSPodSpecs/blob/master/LPMessagingSDK/2.7.0.20.1078/LPMessagingSDK.podspec) is linked to this repository. If this repository is incorrect, then your podspec may need to be fixed.

**Comment by nirlachman-liveperson** [comment]
LivePersonInc/iOSPodSpecs is our repository for pod specs the other one is for the official release
