### ISSUE TITLE
Swift 5.1 compiler error

### ISSUE THREAD

**Issue by jdiegors** [LivePersonInc/iOSFrameworks#11]
I have the next error:
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: .../Pods/LPMessagingSDK/LPMessagingSDK/LPMessagingSDK.framework/Modules/LPMessagingSDK.swiftmodule/x86_64.swiftmodule

Xcode Version: 11
SDK version: LPMessagingSDK (4.1.0.0.250-Swift-5.0)

Which SDK version I need to install with the new Xcode?

**Comment by luandrecast-lp** [comment]
@jdiegors please use tag `4.1.0.0.710-Swift-5.1`
