### ISSUE TITLE
4.1.0.0.710-Swift-5.1 can not run on simulator

### ISSUE THREAD

**Issue by KralMurat** [LivePersonInc/iOSFrameworks#13]
I'm using "4.1.0.0.710-Swift-5.1" to be able to run my project on xCode 11 but in "4.1.0.0.710-Swift-5.1" does not have simulator support. I can only run it on physical devices. Can you please implement simulator support for Swift 5.1 too?

**Comment by luandrecast-lp** [comment]
can you describe your project? is it on objective-C or Swift?  is there a specific error you are seeing?

**Comment by KralMurat** [comment]
The project is pure Swift, and it was working perferctly fine with xCode10.3. Now I'm trying to run it in xCode11. So I had to upgrade it to Swift5.1

When I run it on device with "4.1.0.0.710-Swift-5.1" in xCode11, it works fine. But when I try to run it on simulator, I'm getting "LPAMSFacadeDelegate" can not be found error.

PS: I'm not sure if this is the problem but I realized that  in previous versions' Headers folders, I can see LPMessagingSDK-Device-Swift, LPMessagingSDK-Simulator-Swift.h, LPMessagingSDK-Swift.h and LPMessagingSDK.h files. But in "4.1.0.0.710-Swift-5.1" I can only see LPMessagingSDK-Swift.h and LPMessagingSDK.h these 2 files, I can't see these 2 headers: LPMessagingSDK-Device-Swift, LPMessagingSDK-Simulator-Swift.h. And it's same for all headers in LPAMS.framework, LPInfra.framework, LPMessagingSDK.framework and LPMonitoring.framework.

**Comment by luandrecast-lp** [comment]
Are you using any dependency manager or manually adding the frameworks?

**Comment by KralMurat** [comment]
I'm manually adding frameworks. I couldn't able to install "4.1.0.0.710-Swift-5.1" via Cocoapods, I always get his error: 

Pre-downloading: `LPMessagingSDK` from `https://github.com/LivePersonInc/iOSFrameworks`, tag `4.1.0.0.710-Swift-5.1`

[!] Unable to find a specification for 'LPMessagingSDK'.

**Comment by KralMurat** [comment]
I finally able to install it via Cocoapods and it works with simulator.
