### ISSUE TITLE
Binary is incompatible with Swift 5.1.2

### ISSUE THREAD

**Issue by andproff** [LivePersonInc/iOSFrameworks#14]
There are no any modules compatible with last stable Swift 5.1.2
`Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: .../Pods/LPMessagingSDK/LPMessagingSDK/LPMessagingSDK.framework/Modules/LPMessagingSDK.swiftmodule/arm64-apple-ios.swiftmodule`

**Comment by luandrecast-lp** [comment]
please use tag **5.0.0.960-Swift-5.1.2**
