### ISSUE TITLE
Minimum deployment target is ios 11.0

### ISSUE THREAD

**Issue by mertnesvat** [LivePersonInc/iOSFrameworks#16]
Hello, when we installed 5.1.2 swift compiled version of the frame work I'm getting error (I'm not able to build the project that's why!)
"Compiling for iOS 10.0, but module 'LPMessagingSDK' has a minimum deployment target of iOS 11.0:"
We have to support iOS version 10 and newer.
So how this problem could be solved? Do I have a option of using older framework with new XCode releases?

**Comment by luandrecast-lp** [comment]
closed. see https://github.com/LivePersonInc/iOSPodSpecs/issues/6
