### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [LivePersonInc/iOSFrameworks#17]
I could not able to compile the code. Using xcode 11.3.1 and code is compatible to swift 4.2
Which pod version is compatible?

**Comment by randymclainLP** [comment]
I am sorry you had this issue.. All of our Library versions (in recent times) have tags annotated with the Swift compiler version.  You will want any (preferably the latest) version with the tag annotated with "Swift-5.1.3".  This will work with Xcode 11.3.0 or Xcode 11.3.1.  Cheers!
