### ISSUE TITLE
Misalignment when Chat is Embedded within Tabbar

### ISSUE THREAD

**Issue by fssilva** [LivePersonInc/iOSFrameworks#2]
There's a misalignment when the framework is embedded within another view e.g.  Tabbar. I attached three screenshots. The first screenshot shows the writing box in a correct position. The second shows the misalignment  when the keyboard is displayed. The third shows the same behaior but the chat is displayed as a standalone view controller. 

<img width="376" alt="screen shot 2018-03-12 at 09 27 52" src="https://user-images.githubusercontent.com/589306/37272839-356b2b10-25d8-11e8-9a8a-0be1baac205f.png">

<img width="397" alt="screen shot 2018-03-12 at 09 27 40" src="https://user-images.githubusercontent.com/589306/37272845-39ccbae8-25d8-11e8-8efc-432bd4049fb8.png">

<img width="403" alt="screen shot 2018-03-12 at 09 31 02" src="https://user-images.githubusercontent.com/589306/37272847-3bfc5b70-25d8-11e8-8473-d06d7a2ad865.png">

**Comment by nirlachman-liveperson** [comment]
@fssilva  please contact LP Support.
Thanks

**Comment by luandrecast-lp** [comment]
@fssilva please check the latest sdk version addressing this issue (SDK 4.0)
